// these classes were generated by the type dump sample code: http://ismods.com/phpBB3/viewtopic.php?f=22&t=27
namespace LavishSettings
{
    public class Attribute : LavishSettings.Node
    {
        public System.String Key { get; }
        public System.String Value { get; }
    }
    public class Comment : LavishSettings.Node
    {
    }
    public class Node
    {
        public void Erase();
        public LavishSettings.Node Next { get; }
        public LavishSettings.NodeTypeEnum NodeType { get; }
        public LavishSettings.Node Parent { get; }
        public LavishSettings.Node Previous { get; }
    }
    public enum NodeTypeEnum
    {
        Any = 0,
        Attribute = 4,
        Comment = 1,
        Set = 2,
        Setting = 3,
    }
    public class Set : LavishSettings.Node
    {
        public LavishSettings.Attribute AddAttribute(System.String key, System.String value);
        public LavishSettings.Setting AddSetting(System.String key, System.String value);
        public LavishSettings.Set AddSet(System.String key);
        public void Clear();
        public LavishSettings.Node FindChild(System.String key);
        public LavishSettings.Setting FindSetting(System.String key);
        public LavishScript2.Table GetSets();
        public LavishScript2.Table GetSettings();
        public void ReadXMLFromFile(System.String filename);
        public void WriteXMLToFile(System.String filename);
        public static LavishSettings.Set GetByID(System.UInt32 id);
        public System.UInt32 ID { get; }
        public System.String Key { get; set; }
        public static LavishSettings.Set Root { get; }
    }
    public class Setting : LavishSettings.Node
    {
        public LavishSettings.Attribute AddAttribute(System.String key, System.String value);
        public LavishSettings.Attribute FindAttribute(System.String key);
        public LavishScript2.Table GetAttributes();
        public System.String Key { get; set; }
        public System.String Value { get; set; }
    }

}
